name: sportiq
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0
  # LAB 7: HTTP client for REST API integration
  http: ^1.1.0
  # URL launcher for email/sms/call
  url_launcher: ^6.1.12
  # FAB speed dial
  flutter_speed_dial: ^7.0.0
  # Wakelock control
  wakelock_plus: ^1.4.0
  # Image picker for gallery & camera
  image_picker: ^1.1.0
  # Local file storage
  path_provider: ^2.0.14
  # LAB 8: Notifications
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.0
  # LAB 9: QR scanning
  mobile_scanner: ^5.0.0
  permission_handler: ^12.0.1
  # Notifications UI Badge
  badges: ^3.1.2
  # Date formatting
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/legal/privacy_policy.md
    - assets/legal/terms_of_service.md

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path_ios: assets/branding/app_icon_ios.png

flutter_native_splash:
  color: "#0B1B2B"
  image: assets/branding/splash_logo.png
  ios: true
  android: false
  web: false
  fullscreen: true
