// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjP5P6IPL4SJQbSfpCQh6b5r2ji1SKP_c',
    appId: '1:443453980990:web:88f18f0d8644f6f33d2c6f',
    messagingSenderId: '443453980990',
    projectId: 'sportiq-824eb',
    authDomain: 'sportiq-824eb.firebaseapp.com',
    storageBucket: 'sportiq-824eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyd15alev6WudhDamrDrgV3czddGypPE',
    appId: '1:443453980990:android:1ec8b463d02c7d7a3d2c6f',
    messagingSenderId: '443453980990',
    projectId: 'sportiq-824eb',
    storageBucket: 'sportiq-824eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXraRkdLcbqf2PyY2RfZmGFdXCpmpXK0',
    appId: '1:443453980990:ios:c8db69165a94ec733d2c6f',
    messagingSenderId: '443453980990',
    projectId: 'sportiq-824eb',
    storageBucket: 'sportiq-824eb.firebasestorage.app',
    iosBundleId: 'com.example.sportiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgXraRkdLcbqf2PyY2RfZmGFdXCpmpXK0',
    appId: '1:443453980990:ios:c8db69165a94ec733d2c6f',
    messagingSenderId: '443453980990',
    projectId: 'sportiq-824eb',
    storageBucket: 'sportiq-824eb.firebasestorage.app',
    iosBundleId: 'com.example.sportiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjP5P6IPL4SJQbSfpCQh6b5r2ji1SKP_c',
    appId: '1:443453980990:web:aed17a17d08679e33d2c6f',
    messagingSenderId: '443453980990',
    projectId: 'sportiq-824eb',
    authDomain: 'sportiq-824eb.firebaseapp.com',
    storageBucket: 'sportiq-824eb.firebasestorage.app',
  );
}
